- name: Install depends
  apt: name={{ item }} state=present
  with_items: [python-virtualenv, python-dev, libffi-dev, libssl-dev]

- name: Create the buildbot user
  user: name={{ buildbot_user }} home={{ buildbot_home }}

- name: Install buildbot
  become: yes
  become_user: "{{ buildbot_user }}"
  pip: name={{ item }} virtualenv={{ buildbot_home }}/env state=latest
  with_items:
    - setuptools
    - pip
    - "buildbot[bundle]"
  notify:
    - Restart Buildbot

- name: create buildbot folder
  become: yes
  become_user: "{{ buildbot_user }}"
  file: path={{ buildbot_home }}/master state=directory

- name: Install buildbot master config
  become: yes
  become_user: "{{ buildbot_user }}"
  copy: src={{ item }} dest={{ buildbot_home }}/master/{{ item }}
  with_items:
    - buildbot.tac
    - master.py
    - extras/
  notify:
    - Restart Buildbot

- name: Install buildbot secrets
  become: yes
  become_user: "{{ buildbot_user }}"
  template: src=secrets.json dest={{ buildbot_home }}/master/secrets.json
  notify:
    - Restart Buildbot

- name: Install buildbot service
  template: src=buildbot.service dest=/etc/systemd/system/{{ buildbot_service }}.service
  notify:
    - Reload Systemd
    - Restart Buildbot

- meta: flush_handlers

- name: Start and enable buildbot
  service: name={{ buildbot_service }} state=started enabled=yes
